#!/bin/bash

set -e
set -o pipefail

program="$1"
frames="${2:-50}"
colors="${3:-256}"
outname="$(echo "$program" |sed s/.fs$//g).gif"

if [ -z "$program" ]; then
	echo "Usage: $1 PROGRAM [FRAMES [COLORS]]" >&2
	exit 1
fi

tmpdir="$(mktemp -d --suffix .sfgif)"
trap "{ rm -f \"$tmpdir\"/frame_*.ppm && rmdir \"$tmpdir\"; }" EXIT

echo "Generating frames..."
seq -f %05g 1 $frames \
	|xargs -n1 -t -P$(nproc) -I '{}' sh -c \
	'./sf ": t $(dc -e "2k{} 1-50/p") ;" "'"$program"'" > "'"$tmpdir"'/frame_{}.ppm"'

echo "Building animation \"$outname\"..."
convert -delay 2 -loop 0 \
	$(find "$tmpdir" -mindepth 1 -maxdepth 1 |sort) -dither FloydSteinberg \
	-colors "$colors" \
	"$outname"

echo "Done!"
